name: resume_crafter
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  appwrite: ^12.0.4
  collection: ^1.18.0
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_facebook_auth: ^7.0.1
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  formz: ^0.7.0
  freezed_annotation: ^2.4.4
  get_it: ^7.7.0
  go_router: ^14.2.1
  google_sign_in: ^6.2.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  linkedin_login: ^3.0.5
  sign_in_button: ^3.2.0
  uuid: ^4.5.0
  month_picker_dialog: ^5.1.3
  linkfy_text: ^1.1.5
  pdf: ^3.11.1

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0

dependency_overrides:
  intl: ^0.19.0

flutter:
  uses-material-design: true
  generate: true
